# Generated by Django 5.1.15 on 2026-08-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("councils", "0002_load_london_boroughs"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataLoadRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_file_path", models.CharField(max_length=500)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("row_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="load_runs",
                        to="councils.council",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SpendTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("beneficiary_name", models.CharField(max_length=255)),
                ("amount_gbp", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "directorate",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("category", models.CharField(blank=True, default="", max_length=255)),
                (
                    "sub_category",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="councils.council",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["council", "date"],
                        name="spend_spend_council_38f8fc_idx",
                    ),
                    models.Index(
                        fields=["council", "amount_gbp"],
                        name="spend_spend_council_cab151_idx",
                    ),
                ],
            },
        ),
    ]
