# Generated by Django 5.2.17 on 2026-09-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spend", "0003_beneficiary_name_trgm_fastupdate_off"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataloadrun",
            name="source_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
