# Generated by Django 5.1.15 on 2026-08-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("councils", "0002_load_london_boroughs"),
    ]

    operations = [
        migrations.AddField(
            model_name="councilcoverage",
            name="earliest_transaction_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="councilcoverage",
            name="last_loaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="councilcoverage",
            name="latest_transaction_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
