# Generated by Django 5.1.15 on 2026-08-30 16:36
#
# `default="london"` is a one-off backfill for the 32 pre-existing rows,
# not a lasting default (see `region` in models.py). Unscoped (no gss_code
# filter): replaying this migration once non-London councils exist would
# wrongly re-stamp them all to "london".

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("councils", "0003_councilcoverage_earliest_transaction_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="council",
            name="region",
            field=models.CharField(
                choices=[
                    ("north_east", "North East"),
                    ("north_west", "North West"),
                    ("yorkshire_humber", "Yorkshire and the Humber"),
                    ("east_midlands", "East Midlands"),
                    ("west_midlands", "West Midlands"),
                    ("east_of_england", "East of England"),
                    ("london", "London"),
                    ("south_east", "South East"),
                    ("south_west", "South West"),
                ],
                default="london",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
