# Generated by Django 5.1.15 on 2026-08-30 16:36
#
# `default="london"` below is a one-off backfill for the 32 pre-existing
# (all-London pilot) rows, not a lasting model-level default -- see the
# `region` field's comment in models.py. Note this backfill isn't scoped to
# those specific rows (no gss_code/E09 filter): if this migration is ever
# reversed and reapplied, it will re-stamp *every* Council row that exists
# at that moment to "london", not just the original 32. Fine for a one-way
# forward migration in normal operation; would be wrong to replay blindly
# once councils outside London exist.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("councils", "0003_councilcoverage_earliest_transaction_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="council",
            name="region",
            field=models.CharField(
                choices=[
                    ("north_east", "North East"),
                    ("north_west", "North West"),
                    ("yorkshire_humber", "Yorkshire and the Humber"),
                    ("east_midlands", "East Midlands"),
                    ("west_midlands", "West Midlands"),
                    ("east_of_england", "East of England"),
                    ("london", "London"),
                    ("south_east", "South East"),
                    ("south_west", "South West"),
                ],
                default="london",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
